services:
  mysql:
    image: mysql:8.0
    container_name: airport_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: airport_mgmt
      MYSQL_USER: airport_user
      MYSQL_PASSWORD: airport_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: airport_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5

  backend:
    build: ./backend
    container_name: airport_backend
    restart: always
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: mysql+aiomysql://airport_user:airport_pass@mysql:3306/airport_mgmt
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: your-secret-key-change-in-production
      ENVIRONMENT: development
      OPENAIP_API_KEY: ${OPENAIP_API_KEY:-}
    volumes:
      - ./backend:/app
      - ./data:/data
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: ./backend
    container_name: airport_celery_worker
    restart: always
    environment:
      DATABASE_URL: mysql+aiomysql://airport_user:airport_pass@mysql:3306/airport_mgmt
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./backend:/app
      - ./data:/data
    depends_on:
      - mysql
      - redis
      - backend
    command: celery -A app.celery_app worker --loglevel=info

  celery_beat:
    build: ./backend
    container_name: airport_celery_beat
    restart: always
    environment:
      DATABASE_URL: mysql+aiomysql://airport_user:airport_pass@mysql:3306/airport_mgmt
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./backend:/app
      - ./data:/data
    depends_on:
      - mysql
      - redis
      - backend
    command: celery -A app.celery_app beat --loglevel=info

  flower:
    build: ./backend
    container_name: airport_flower
    restart: always
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - celery_worker
    command: celery -A app.celery_app flower

  frontend:
    build: ./frontend
    container_name: airport_frontend
    restart: always
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8001/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start

volumes:
  mysql_data:
  redis_data: