version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: airport_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: airport_lights
      MYSQL_USER: airport_user
      MYSQL_PASSWORD: airport_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
