services:
  mysql:
    image: mysql:8.0
    container_name: airport_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: airport_mgmt
      MYSQL_USER: airport_user
      MYSQL_PASSWORD: airport_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: airport_backend
    restart: always
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: mysql+aiomysql://airport_user:airport_pass@mysql:3306/airport_mgmt
      SECRET_KEY: your-secret-key-change-in-production
      ENVIRONMENT: development
      OPENAIP_API_KEY: ${OPENAIP_API_KEY:-}
    volumes:
      - ./backend:/app
      - ./data:/data
    depends_on:
      mysql:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: airport_frontend
    restart: always
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8001/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start

volumes:
  mysql_data: