version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: airport_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: airport_mgmt
      MYSQL_USER: airport_user
      MYSQL_PASSWORD: airport_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: