"""Initial tables

Revision ID: 7f154f6e78b8
Revises: 
Create Date: 2025-10-21 09:51:37.631149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f154f6e78b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airspace_intersections')
    op.drop_table('airspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airspaces',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('airport_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('icao_designator', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('airspace_class', mysql.ENUM('CLASS_A', 'CLASS_B', 'CLASS_C', 'CLASS_D', 'CLASS_E', 'CLASS_F', 'CLASS_G', 'SPECIAL_USE'), nullable=False),
    sa.Column('airspace_type', mysql.ENUM('CTR', 'TMA', 'CTA', 'ATZ', 'PROHIBITED', 'RESTRICTED', 'DANGER', 'MOA', 'TSA', 'TRA', 'FIR', 'UIR', 'ADIZ', 'TFR', 'GLIDING', 'PARACHUTE', 'AERIAL_WORK', 'AWY', 'NAV_WARN'), nullable=False),
    sa.Column('lower_limit_value', mysql.FLOAT(), nullable=False),
    sa.Column('lower_limit_reference', mysql.ENUM('MSL', 'AGL', 'FL', 'SFC', 'UNL', 'NOTAM'), nullable=False),
    sa.Column('lower_limit_unit', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('upper_limit_value', mysql.FLOAT(), nullable=False),
    sa.Column('upper_limit_reference', mysql.ENUM('MSL', 'AGL', 'FL', 'SFC', 'UNL', 'NOTAM'), nullable=False),
    sa.Column('upper_limit_unit', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('lower_limit_meters', mysql.FLOAT(), nullable=True),
    sa.Column('upper_limit_meters', mysql.FLOAT(), nullable=True),
    sa.Column('geometry', sa.NullType(), nullable=False),
    sa.Column('area_sq_km', mysql.FLOAT(), nullable=True),
    sa.Column('center_latitude', mysql.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('center_longitude', mysql.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('active_times', mysql.JSON(), nullable=True),
    sa.Column('frequencies', mysql.JSON(), nullable=True),
    sa.Column('controlling_authority', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_info', mysql.JSON(), nullable=True),
    sa.Column('restrictions', mysql.JSON(), nullable=True),
    sa.Column('properties', mysql.JSON(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_temporary', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('valid_from', mysql.DATETIME(), nullable=True),
    sa.Column('valid_until', mysql.DATETIME(), nullable=True),
    sa.Column('regulation_reference', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('aip_reference', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('source', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('source_updated', mysql.DATETIME(), nullable=True),
    sa.Column('border_color', mysql.VARCHAR(length=7), nullable=True),
    sa.Column('fill_color', mysql.VARCHAR(length=7), nullable=True),
    sa.Column('opacity', mysql.FLOAT(), nullable=True),
    sa.Column('display_priority', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_airspace_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], name='fk_airspaces_airport_id_airports', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_airspaces_created_by_users'),
    sa.ForeignKeyConstraint(['parent_airspace_id'], ['airspaces.id'], name='fk_airspaces_parent_airspace_id_airspaces'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('airspace_intersections',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('airspace1_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('airspace2_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('intersection_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('overlap_lower_meters', mysql.FLOAT(), nullable=True),
    sa.Column('overlap_upper_meters', mysql.FLOAT(), nullable=True),
    sa.Column('intersection_geometry', sa.NullType(), nullable=False),
    sa.Column('intersection_area_sq_km', mysql.FLOAT(), nullable=True),
    sa.Column('is_conflict', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('conflict_notes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['airspace1_id'], ['airspaces.id'], name=op.f('fk_airspace_intersections_airspace1_id_airspaces')),
    sa.ForeignKeyConstraint(['airspace2_id'], ['airspaces.id'], name=op.f('fk_airspace_intersections_airspace2_id_airspaces')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###